### ISSUE TITLE
Support file formData

### ISSUE THREAD

**Issue by kylef** [apiaryio/fury-adapter-swagger#127]
Parameters that are file type in formData are currently not supported.

```yaml
 parameters:
    - name: image
      in: formData
      required: true
      type: file
```
