### ISSUE TITLE
Support multiple request headers

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/fury-adapter-swagger#129]
There is no support for multiple response headers of the same name in Swagger 2.0, but there is a way how to have multiple request headers of the same name:

```yaml
paths:
  /honey:
    get:
      parameters:
        - name: X-Multiple
          in: header
          x-example: foo
          type: string
        - name: X-Multiple
          in: header
          x-example: bar
          type: string
```

This syntax returns error though:

```
Validation failed. /paths/honey/get has duplicate parameters
Validation failed. Found multiple header parameters named "X-Multiple"
```

Related: https://github.com/OAI/OpenAPI-Specification/issues/1237
